[package]
name = "gpconv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
osm = ["dep:osmio"]

[profile.release]
lto = true
opt-level='z'

#[lib]
#crate-type = ["cdylib"]

[dependencies]
gpx="*"
itertools="*"
lazy_static="*"
osmio={version="*", optional=true}
wasm-bindgen="*"
xml-rs="*"
reqwest-wasm={version="*", features=["blocking"]}